In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import string
import matplotlib.pyplot as plt

In [3]:
df= pd.read_csv('email_spam[1].csv')
df

title  \
0                           ?? the secrets to SUCCESS   
1                     ?? You Earned 500 GCLoot Points   
2                          ?? Your GitHub launch code   
3   [The Virtual Reward Center] Re: ** Clarifications   
4   10-1 MLB Expert Inside, Plus Everything You Ne...   
..                                                ...   
79  Your application for the position of  Child Pr...   
80     Your Kilimall Account is Ready - Shopping Now!   
81  Your Steam account: Access from new web or mob...   
82                 Your uploaded document is rejected   
83   You've Earned a Reward from Bard Explorers India   

                                                 text      type  
0   Hi James,\n\nHave you claim your complimentary...      spam  
1   \nalt_text\nCongratulations, you just earned\n...  not spam  
2   Here's your GitHub launch code, @Mortyj420!\n ...  not spam  
3   Hello,\n \nThank you for contacting the Virtua...  not spam  
4   Hey Prachanda Rawal,\n\nToday's newsletter is ...      spam  
..                                                ...       ...  
79  Dear Maryam, \n\n \n\nI would like to thank yo...  not spam  
80  Dear Customer,\n\nWelcome to Kilimall, Thanks ...  not spam  
81  Dear vladis163rus,\nHere is the Steam Guard co...  not spam  
82  View In Browser | Log in\n \n \n\nSkrill logo\...  not spam  
83  You've received a gift!\nSign in to your Bard ...  not spam  

[84 rows x 3 columns]

In [6]:
df['Target']=df['type'].map({"spam":0,"not spam":1})
df.drop(columns="type",inplace=True)

In [7]:
df.head()

title  \
0                          ?? the secrets to SUCCESS   
1                    ?? You Earned 500 GCLoot Points   
2                         ?? Your GitHub launch code   
3  [The Virtual Reward Center] Re: ** Clarifications   
4  10-1 MLB Expert Inside, Plus Everything You Ne...   

                                                text  Target  
0  Hi James,\n\nHave you claim your complimentary...       0  
1  \nalt_text\nCongratulations, you just earned\n...       1  
2  Here's your GitHub launch code, @Mortyj420!\n ...       1  
3  Hello,\n \nThank you for contacting the Virtua...       1  
4  Hey Prachanda Rawal,\n\nToday's newsletter is ...       0

In [8]:
df.isna().sum()

title     0
text      0
Target    0
dtype: int64

In [10]:
df["Target"].value_counts()

1    58
0    26
Name: Target, dtype: int64

In [21]:
df['text_len']=df.text.str.len()


title  \
0                          ?? the secrets to SUCCESS   
1                    ?? You Earned 500 GCLoot Points   
2                         ?? Your GitHub launch code   
3  [The Virtual Reward Center] Re: ** Clarifications   
4  10-1 MLB Expert Inside, Plus Everything You Ne...   

                                                text  Target  text_len  length  
0  Hi James,\n\nHave you claim your complimentary...       0       302     302  
1  \nalt_text\nCongratulations, you just earned\n...       1       350     350  
2  Here's your GitHub launch code, @Mortyj420!\n ...       1       166     166  
3  Hello,\n \nThank you for contacting the Virtua...       1       399     399  
4  Hey Prachanda Rawal,\n\nToday's newsletter is ...       0      6079    6079

In [22]:
df["text"]=df['text'].str.lower()

In [25]:
df.drop(columns="length",inplace=True)

In [26]:
df

title  \
0                           ?? the secrets to SUCCESS   
1                     ?? You Earned 500 GCLoot Points   
2                          ?? Your GitHub launch code   
3   [The Virtual Reward Center] Re: ** Clarifications   
4   10-1 MLB Expert Inside, Plus Everything You Ne...   
..                                                ...   
79  Your application for the position of  Child Pr...   
80     Your Kilimall Account is Ready - Shopping Now!   
81  Your Steam account: Access from new web or mob...   
82                 Your uploaded document is rejected   
83   You've Earned a Reward from Bard Explorers India   

                                                 text  Target  text_len  
0   hi james,\n\nhave you claim your complimentary...       0       302  
1   \nalt_text\ncongratulations, you just earned\n...       1       350  
2   here's your github launch code, @mortyj420!\n ...       1       166  
3   hello,\n \nthank you for contacting the virtua...       1       399  
4   hey prachanda rawal,\n\ntoday's newsletter is ...       0      6079  
..                                                ...     ...       ...  
79  dear maryam, \n\n \n\ni would like to thank yo...       1       432  
80  dear customer,\n\nwelcome to kilimall, thanks ...       1       466  
81  dear vladis163rus,\nhere is the steam guard co...       1      1060  
82  view in browser | log in\n \n \n\nskrill logo\...       1      3163  
83  you've received a gift!\nsign in to your bard ...       1       499  

[84 rows x 4 columns]

In [27]:
df.describe()

Target     text_len
count  84.000000    84.000000
mean    0.690476   845.690476
std     0.465074   989.806151
min     0.000000    19.000000
25%     0.000000   312.750000
50%     1.000000   568.000000
75%     1.000000   941.000000
max     1.000000  6079.000000

In [37]:
df.loc[df['text_len']==6079]

title  \
4  10-1 MLB Expert Inside, Plus Everything You Ne...   

                                                text  Target  text_len  
4  hey prachanda rawal,\n\ntoday's newsletter is ...       0      6079

In [35]:
df.describe(include="O")

title                                               text
count        84                                                 84
unique       78                                                 82
top     English  model casting call\nthank you for taking the t...
freq          3                                                  2

In [54]:
import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [58]:
str2=df['text'][8]
str2

'\nlogo image\nsenol yildirim,\n\nsomeone signed-in to your account.\n\nwhen: jul 06, 2023 07:34 pm turkey time\ndevice: amazon shopping app for android\nnear: manisa, turkey\nif this was you, you can disregard this message. otherwise, please let us know.'

In [57]:
l1 = [i for i in str2 if i not in string.punctuation]  #list comprehension
print(l1)
"".join(l1)

['\n', 'l', 'o', 'g', 'o', ' ', 'i', 'm', 'a', 'g', 'e', '\n', 's', 'e', 'n', 'o', 'l', ' ', 'y', 'i', 'l', 'd', 'i', 'r', 'i', 'm', '\n', '\n', 's', 'o', 'm', 'e', 'o', 'n', 'e', ' ', 's', 'i', 'g', 'n', 'e', 'd', 'i', 'n', ' ', 't', 'o', ' ', 'y', 'o', 'u', 'r', ' ', 'a', 'c', 'c', 'o', 'u', 'n', 't', '\n', '\n', 'w', 'h', 'e', 'n', ' ', 'j', 'u', 'l', ' ', '0', '6', ' ', '2', '0', '2', '3', ' ', '0', '7', '3', '4', ' ', 'p', 'm', ' ', 't', 'u', 'r', 'k', 'e', 'y', ' ', 't', 'i', 'm', 'e', '\n', 'd', 'e', 'v', 'i', 'c', 'e', ' ', 'a', 'm', 'a', 'z', 'o', 'n', ' ', 's', 'h', 'o', 'p', 'p', 'i', 'n', 'g', ' ', 'a', 'p', 'p', ' ', 'f', 'o', 'r', ' ', 'a', 'n', 'd', 'r', 'o', 'i', 'd', '\n', 'n', 'e', 'a', 'r', ' ', 'm', 'a', 'n', 'i', 's', 'a', ' ', 't', 'u', 'r', 'k', 'e', 'y', '\n', 'i', 'f', ' ', 't', 'h', 'i', 's', ' ', 'w', 'a', 's', ' ', 'y', 'o', 'u', ' ', 'y', 'o', 'u', ' ', 'c', 'a', 'n', ' ', 'd', 'i', 's', 'r', 'e', 'g', 'a', 'r', 'd', ' ', 't', 'h', 'i', 's', ' ', 'm', 'e', 

'\nlogo image\nsenol yildirim\n\nsomeone signedin to your account\n\nwhen jul 06 2023 0734 pm turkey time\ndevice amazon shopping app for android\nnear manisa turkey\nif this was you you can disregard this message otherwise please let us know'

In [124]:
def remove_punctu(text):
    text="".join([char for char in text if char not in string.punctuation])
    return text
df['new_text']=df['text'].apply(lambda x: remove_punctu(x))
df.head()

title  \
0                          ?? the secrets to SUCCESS   
1                    ?? You Earned 500 GCLoot Points   
2                         ?? Your GitHub launch code   
3  [The Virtual Reward Center] Re: ** Clarifications   
4  10-1 MLB Expert Inside, Plus Everything You Ne...   

                                                text  Target  text_len  \
0  hi james,\n\nhave you claim your complimentary...       0       302   
1  \nalt_text\ncongratulations, you just earned\n...       1       350   
2  here's your github launch code, @mortyj420!\n ...       1       166   
3  hello,\n \nthank you for contacting the virtua...       1       399   
4  hey prachanda rawal,\n\ntoday's newsletter is ...       0      6079   

                                            new_text  \
0  hi james\n\nhave you claim your complimentary ...   
1  \nalttext\ncongratulations you just earned\n50...   
2  heres your github launch code mortyj420\n \nan...   
3  hello\n \nthank you for contacting the virtual...   
4  hey prachanda rawal\n\ntodays newsletter is ja...   

                                           new_title  
0                          ?? the secrets to success  
1                    ?? you earned 500 gcloot points  
2                         ?? your github launch code  
3  [the virtual reward center] re: ** clarifications  
4  10-1 mlb expert inside, plus everything you ne...

In [63]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [64]:
import nltk

In [65]:
from nltk.corpus import stopwords
nltk.download("stopwords")
print(stopwords.words("english"),len(stopwords.words("english")))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mvara\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she

In [66]:
cv=CountVectorizer(stop_words="english")

In [67]:
cv.fit(df['new_text'])

CountVectorizer(stop_words='english')

In [68]:
X=cv.transform(df['new_text'])

In [71]:
X

<84x2699 sparse matrix of type '<class 'numpy.int64'>'
	with 4781 stored elements in Compressed Sparse Row format>

In [77]:
X[1]

<1x2699 sparse matrix of type '<class 'numpy.int64'>'
	with 38 stored elements in Compressed Sparse Row format>

In [80]:
Xset=df['new_text'].values
# Xset/

In [103]:
y=df['Target']

In [104]:

yset=df['Target']
yset=yset.astype(int)


In [105]:
type(yset)



pandas.core.series.Series

In [150]:
trainx=cv.transform(df['text'])
trainx

<84x262 sparse matrix of type '<class 'numpy.int64'>'
	with 739 stored elements in Compressed Sparse Row format>

In [106]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=(X,y,test_size=0.2,random_state=22)

In [107]:
nb=MultinomialNB()

In [109]:
nb.fit(X_train,y_train)

MultinomialNB()

In [114]:
pred=nb.predict(X_test)
pred

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0],
      dtype=int64)

In [115]:
y_test

58    1
13    1
49    1
0     0
74    0
51    1
82    1
6     1
35    0
54    1
41    0
65    1
76    0
25    0
12    1
43    1
81    1
7     0
24    1
79    1
57    0
Name: Target, dtype: int64

In [152]:
XSet_train,XSet_test,ySet_train,ySet_test = train_test_split(trainx,y,test_size=0.2, random_state=42)

In [156]:
nb.fit(XSet_train,ySet_train)

MultinomialNB()

In [158]:
pred2=nb.predict(XSet_test)
pred2

array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [160]:
ySet_test

73    1
0     0
58    1
22    0
12    1
70    1
10    1
18    1
4     0
65    1
40    0
47    1
35    0
81    1
55    0
54    1
33    1
Name: Target, dtype: int64

In [162]:
accuracyScore = accuracy_score(pred2,ySet_test)*100

print("Prediction Accuracy :",accuracyScore)

Prediction Accuracy : 64.70588235294117


In [116]:
accuracyScore = accuracy_score(pred,y_test)*100

print("Prediction Accuracy :",accuracyScore)

Prediction Accuracy : 85.71428571428571


In [117]:
from sklearn.metrics import confusion_matrix

In [118]:
confusion_matrix(pred,y_test)

array([[ 7,  2],
       [ 1, 11]], dtype=int64)

In [119]:
df.head()

title  \
0                          ?? the secrets to SUCCESS   
1                    ?? You Earned 500 GCLoot Points   
2                         ?? Your GitHub launch code   
3  [The Virtual Reward Center] Re: ** Clarifications   
4  10-1 MLB Expert Inside, Plus Everything You Ne...   

                                                text  Target  text_len  \
0  hi james,\n\nhave you claim your complimentary...       0       302   
1  \nalt_text\ncongratulations, you just earned\n...       1       350   
2  here's your github launch code, @mortyj420!\n ...       1       166   
3  hello,\n \nthank you for contacting the virtua...       1       399   
4  hey prachanda rawal,\n\ntoday's newsletter is ...       0      6079   

                                            new_text  
0  hi james\n\nhave you claim your complimentary ...  
1  \nalttext\ncongratulations you just earned\n50...  
2  heres your github launch code mortyj420\n \nan...  
3  hello\n \nthank you for contacting the virtual...  
4  hey prachanda rawal\n\ntodays newsletter is ja...

In [127]:
def remove_punctu(title):
    text="".join([char for char in title if char not in string.punctuation])
    return title.lower()
df['new_title']=df['title'].apply(lambda x: remove_punctu(x))
df.head()

title  \
0                          ?? the secrets to SUCCESS   
1                    ?? You Earned 500 GCLoot Points   
2                         ?? Your GitHub launch code   
3  [The Virtual Reward Center] Re: ** Clarifications   
4  10-1 MLB Expert Inside, Plus Everything You Ne...   

                                                text  Target  text_len  \
0  hi james,\n\nhave you claim your complimentary...       0       302   
1  \nalt_text\ncongratulations, you just earned\n...       1       350   
2  here's your github launch code, @mortyj420!\n ...       1       166   
3  hello,\n \nthank you for contacting the virtua...       1       399   
4  hey prachanda rawal,\n\ntoday's newsletter is ...       0      6079   

                                            new_text  \
0  hi james\n\nhave you claim your complimentary ...   
1  \nalttext\ncongratulations you just earned\n50...   
2  heres your github launch code mortyj420\n \nan...   
3  hello\n \nthank you for contacting the virtual...   
4  hey prachanda rawal\n\ntodays newsletter is ja...   

                                           new_title  
0                          ?? the secrets to success  
1                    ?? you earned 500 gcloot points  
2                         ?? your github launch code  
3  [the virtual reward center] re: ** clarifications  
4  10-1 mlb expert inside, plus everything you ne...

In [129]:
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [142]:
import string

df['title'] = df['title'].str.translate(str.maketrans('', '', string.punctuation)).str.lower()


In [143]:
df

title  \
0                              the secrets to success   
1                        you earned 500 gcloot points   
2                             your github launch code   
3        the virtual reward center re  clarifications   
4   101 mlb expert inside plus everything you need...   
..                                                ...   
79  your application for the position of  child pr...   
80       your kilimall account is ready  shopping now   
81  your steam account access from new web or mobi...   
82                 your uploaded document is rejected   
83    youve earned a reward from bard explorers india   

                                                 text  Target  text_len  \
0   hi james,\n\nhave you claim your complimentary...       0       302   
1   \nalt_text\ncongratulations, you just earned\n...       1       350   
2   here's your github launch code, @mortyj420!\n ...       1       166   
3   hello,\n \nthank you for contacting the virtua...       1       399   
4   hey prachanda rawal,\n\ntoday's newsletter is ...       0      6079   
..                                                ...     ...       ...   
79  dear maryam, \n\n \n\ni would like to thank yo...       1       432   
80  dear customer,\n\nwelcome to kilimall, thanks ...       1       466   
81  dear vladis163rus,\nhere is the steam guard co...       1      1060   
82  view in browser | log in\n \n \n\nskrill logo\...       1      3163   
83  you've received a gift!\nsign in to your bard ...       1       499   

                                             new_text  \
0   hi james\n\nhave you claim your complimentary ...   
1   \nalttext\ncongratulations you just earned\n50...   
2   heres your github launch code mortyj420\n \nan...   
3   hello\n \nthank you for contacting the virtual...   
4   hey prachanda rawal\n\ntodays newsletter is ja...   
..                                                ...   
79  dear maryam \n\n \n\ni would like to thank you...   
80  dear customer\n\nwelcome to kilimall thanks so...   
81  dear vladis163rus\nhere is the steam guard cod...   
82  view in browser  log in\n \n \n\nskrill logo\n...   
83  youve received a gift\nsign in to your bard ex...   

                                            new_title  
0                           ?? the secrets to success  
1                     ?? you earned 500 gcloot points  
2                          ?? your github launch code  
3   [the virtual reward center] re: ** clarifications  
4   10-1 mlb expert inside, plus everything you ne...  
..                                                ...  
79  your application for the position of  child pr...  
80     your kilimall account is ready - shopping now!  
81  your steam account: access from new web or mob...  
82                 your uploaded document is rejected  
83   you've earned a reward from bard explorers india  

[84 rows x 6 columns]

In [144]:
cv.fit(df['title'])

CountVectorizer(stop_words='english')

In [145]:
X1=cv.transform(df["title"])

In [146]:
X1

<84x262 sparse matrix of type '<class 'numpy.int64'>'
	with 342 stored elements in Compressed Sparse Row format>

In [164]:
y1=df['Target']

In [166]:
X1_train,X1_test,y1_train,y1_test=train_test_split(X1,y1,test_size=0.2)

In [167]:
nb.fit(X1_train,y1_train)

MultinomialNB()

In [169]:
pred3=nb.predict(X1_test)
pred3

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0], dtype=int64)

In [170]:
y1_test

14    0
55    0
33    1
18    1
0     0
80    1
15    1
64    1
35    0
31    0
3     1
78    1
34    0
52    1
61    0
37    1
20    0
Name: Target, dtype: int64

In [173]:
accuracy_score(pred3,y1_test)*100

58.82352941176471

In [172]:
confusion_matrix(pred3,y1_test)

array([[5, 4],
       [3, 5]], dtype=int64)